
---
apiVersion: apps/v1
kind: Deployment
metadata:
    creationTimestamp: null
    labels:
        move2kube.konveyor.io/service: awesome-compose
    name: awesome-compose
spec:
    progressDeadlineSeconds: 600
    replicas: {{ index .Values "common" "replicas" }}
    revisionHistoryLimit: 10
    selector:
        matchLabels:
            move2kube.konveyor.io/service: awesome-compose
    strategy:
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 25%
        type: RollingUpdate
    template:
        metadata:
            creationTimestamp: null
            labels:
                move2kube.konveyor.io/service: awesome-compose
            name: awesome-compose
        spec:
            containers:
                - image: quay.io/jefrankl/awesome-compose:latest
                  imagePullPolicy: Always
                  name: awesome-compose
                  ports:
                    - containerPort: 8080
                      protocol: TCP
                  resources: {}
                  terminationMessagePath: /dev/termination-log
                  terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            imagePullSecrets:
                - name: quay-io-imagepullsecret
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
status: {}

...
