
---
apiVersion: v1
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJxdWF5LmlvIjoge30KCX0KfQ==
kind: Secret
metadata:
    creationTimestamp: null
    name: quay-io-imagepullsecret
type: kubernetes.io/dockerconfigjson

...
